### ISSUE TITLE
Cannot change working directory

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#79]
From the Customizer devel branch GUI -- click on **Settings** tab. Before loading ISO, click on **Change** button, select other directory folder and click **Open**. But the working directory cannot be changed.

I tried changing the settings at `/etc/customizer.conf` via Text Editor, then run GUI again to see the changes in GUI--OK. But when trying again to make changes via **Changes** button in GUI, same errors were seen as screenshot below.

![screenshot - 10122014 - 013824 am](https://cloud.githubusercontent.com/assets/1223304/4603756/722e696a-5177-11e4-8c73-e16e8514aa4c.png)

The Terminal returned error as below.

```
sudo customizer-gui
Traceback (most recent call last):
  File "../src/gui.py", line 284, in change_work_dir
NameError: global name 'current' is not defined
```

Based on the debug messages, apparently the variable name `current` is undefined.

**Comment by ghost** [comment]
Just to make this issue clear, the default directory `/home` is working fine.

I had installed two branches--gambas3 and devel--of Customizer on same host system, so I purposedly wanted to change to other directory for each of them (to avoid any conflict).

Then, I found the devel branch doesn't allow me to change the directory..

**Comment by ghost** [comment]
@fluxer 
Took a quick test last weekend, directory can be changed correctly via GUI. Tested using latest devel branch (commit 4fe0a00). Confirmed working therefore closing this issue.

**Comment by ghost** [comment]
I suspect the existing fix may not be effective. The working directory is seen changed in GUI, but changes is _not_ applied immediately.

Details will be posted after I sort my findings properly.

**Comment by ghost** [comment]
I am using the latest devel branch commit ea5d850. With this, I have confirmed that the changes to working directory is only effective _after_ I quit GUI and run it again for second time.

To reproduce the issue, I have tested in three consecutive stages.

Firstly, I tried with default working directory `/home` as it is. Loaded minimal 14.04 ISO image, and `FileSystem` and `ISO` folders are seen created under it. This is normal, OK.

![screenshot-11152014-1-home](https://cloud.githubusercontent.com/assets/1223304/5058277/5e4d68c4-6d24-11e4-87e9-4700ee74d23a.png)

Secondly, I cleaned up and attempted to change working directory via GUI to `/home/try`. Loaded the same ISO image, and one could notice that those folders are being created in previous working directory `/home`. This is _not_ working properly.

![screenshot-11152014-2-try](https://cloud.githubusercontent.com/assets/1223304/5058309/75d12340-6d25-11e4-86d6-27eee3da0fa3.png)

Thirdly, I cleaned up again. This time, I quit GUI once and run GUI again from Terminal. Here, I am _not_ making any changes to working directory (means, it is still set to `/home/try` from previous attempt). Then, I loaded same ISO image and this time extracts to the correct path `/home/try`.

![screenshot-11152014-3-try-again](https://cloud.githubusercontent.com/assets/1223304/5058310/82586740-6d25-11e4-9344-f4614bdf8f19.png)

Below is the Terminal output for all three steps above.

```
trusty@DELL1300:~$ sudo customizer-gui
  => Creating: /home/FileSystem
  => Creating: /home/ISO
  => Creating mount directory
  => Mounting ISO: /home/trusty/Downloads/copy/Ubuntu-i386-14.04-mt86plus.iso
  => Checking ISO
  => Unsquashing filesystem
Parallel unsquashfs: Using 1 processor
65322 inodes (55902 blocks) to write

[==========================================================- ] 55899/55902  99%
created 59931 files
created 12737 directories
created 5373 symlinks
created 0 devices
created 0 fifos
  => Checking architecture
  => Copying ISO files
  => Unmounting: /media/zC56fa
  => Removing: /media/zC56fa
  => Removing: /home/FileSystem
  => Removing: /home/ISO
  => Creating: /home/FileSystem
  => Creating: /home/ISO
  => Creating mount directory
  => Mounting ISO: /home/trusty/Downloads/copy/Ubuntu-i386-14.04-mt86plus.iso
  => Checking ISO
  => Unsquashing filesystem
Parallel unsquashfs: Using 1 processor
65322 inodes (55902 blocks) to write

[==========================================================| ] 55899/55902  99%
created 59931 files
created 12737 directories
created 5373 symlinks
created 0 devices
created 0 fifos
  => Checking architecture
  => Copying ISO files
  => Unmounting: /media/1fBaNR
  => Removing: /media/1fBaNR
  => Removing: /home/FileSystem
  => Removing: /home/ISO
trusty@DELL1300:~$ sudo customizer-gui
[sudo] password for trusty: 
  => Creating: /home/try/FileSystem
  => Creating: /home/try/ISO
  => Creating mount directory
  => Mounting ISO: /home/trusty/Downloads/copy/Ubuntu-i386-14.04-mt86plus.iso
  => Checking ISO
  => Unsquashing filesystem
Parallel unsquashfs: Using 1 processor
65322 inodes (55902 blocks) to write

[==========================================================\ ] 55899/55902  99%
created 59931 files
created 12737 directories
created 5373 symlinks
created 0 devices
created 0 fifos
  => Checking architecture
  => Copying ISO files
  => Unmounting: /media/4k_nCK
  => Removing: /media/4k_nCK
```

Above all, this is what I meant by "The working directory is seen changed in GUI, but changes is not applied immediately." in earlier comment.

**Comment by fluxer** [comment]
Thank you for your input. This issue is caused by me overlooking the changes needed in 989b5ab, reloading the config module after changing the value in the config file should do it, or values in the config module should be updated (config.FILESYSTEM_DIR and config.ISO_DIR) since they depend on the working directory variable (config.WORK_DIR). The fix would be easy and I will look into it tonight.

**Comment by fluxer** [comment]
The issue should be solved.

**Comment by ghost** [comment]
@fluxer
No, the issue still can be reproduced with latest commit 5b01a96. This time, GUI behaviour changed. I attempted to set to `/home/try` first. After ISO was fully extracted, GUI settings reverted to `/home`.

In other words, Customizer still failed to detect changes made via GUI (although it correctly "amend" the actual path by itself). The workaround is still same: change working directory, quit GUI and re-run GUI.

P.S.: I ran out of time already. I will follow up again next week or so.

**Comment by fluxer** [comment]
@clearkimura 
I have tested the code before pushing the commit, it does make Customizer to put working directories under the newly asigned but I have not payed attention to the GUI (the widget that indicates what is the working directory) as I was kind of in a hurry. The GUI widget may not be update but it should work but I will check again what's going on soon.

**Comment by ghost** [comment]
@fluxer 
Take your time. I will post my finding details and screenshots in coming weeks.

**UPDATED** Added screenshots when testing with earlier commit.

Before/while loading ISO with working path `/home/try`
![screenshot-11222014-try-1](https://cloud.githubusercontent.com/assets/1223304/5154240/0e0b5080-728b-11e4-8983-0a49b1108178.png)

After loading ISO, the working path revert to `/home` (initial default)
![screenshot-11222014-try-2b](https://cloud.githubusercontent.com/assets/1223304/5154249/af403786-728b-11e4-8715-5459521add73.png)

**Comment by fluxer** [comment]
The latest issue seems to be reproducable only with the compiled binaries and, from my experience, only half of it - the working directory is changed in the GUI but is not respected at all (have not checked the config). The Python scripts however work as expected. Looks like it is another issue that is related to Nuitka. I think I will have to make it optional so if the state of Nuitka improves in the future it is ready to be used and unbundle the copy of it in the tree, that means that the the scripts will be installed. I'll look into it again soon.

**Comment by ghost** [comment]
@fluxer 

> The latest issue seems to be reproducable only with the compiled binaries [..]

Yes, you are right. I had installed latest commit aa6aaeb (after you had removed `Nuitka`) from devel branch and tested it using same ISO image. This time, it worked like charm!

Before/while loading ISO with working path /home/try
![screenshot-11222014-try-5](https://cloud.githubusercontent.com/assets/1223304/5154262/5db88b4c-728c-11e4-95ed-13a91ddf0f89.png)

After loading ISO, the working path remained at /home (same as previously set path)
![screenshot-11222014-try-6](https://cloud.githubusercontent.com/assets/1223304/5154263/896a76ba-728c-11e4-82b8-78ec4dac70a9.png)

I guess that had solved this issue for good. Issue closed.
